package by.bsuir.warehouse.common.protocol;

public enum Action {

    LOGIN,
    LOGOUT,

    REGISTER,
    GET_PENDING_USERS,
    APPROVE_USER,
    REJECT_USER,

    GET_ALL_USERS,
    GET_USER_BY_ID,
    CREATE_USER,
    UPDATE_USER,
    DEACTIVATE_USER,
    DELETE_USER,
    GET_ALL_ROLES,

    GET_MY_PROFILE,
    UPDATE_MY_PROFILE,

    // Проверка старого пароля при смене
    VERIFY_PASSWORD,

    GET_ALL_PRODUCTS,
    GET_PRODUCT_BY_ID,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    GET_ALL_WAREHOUSES,
    GET_WAREHOUSE_BY_ID,
    CREATE_WAREHOUSE,
    UPDATE_WAREHOUSE,
    DELETE_WAREHOUSE,

    GET_STOCK_BY_WAREHOUSE,
    GET_STOCK_ALL,

    GET_ALL_SUPPLIERS,
    CREATE_SUPPLIER,
    UPDATE_SUPPLIER,
    DELETE_SUPPLIER,

    GET_ALL_CUSTOMERS,
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,

    PROCESS_INCOME,
    PROCESS_OUTCOME,
    PROCESS_TRANSFER,
    PROCESS_INVENTORY,
    GET_DOCUMENTS,
    GET_DOCUMENT_BY_ID,

    GET_FORECAST_ALL,
    GET_FORECAST_BY_WAREHOUSE,
    RECALCULATE_FORECAST,

    GET_REPORT_TURNOVER,
    GET_REPORT_DEFICIT,
    EXPORT_DOCUMENTS_CSV,
    GET_SALES_REPORT,
    GET_ANALYTICS,

    GET_AUDIT_LOG,
    BACKUP_DATABASE
}